### ISSUE TITLE
Submit the JOSS paper

### ISSUE THREAD

**Issue by adrn** [adrn/schwimmbad#11]
Write and submit a JOSS paper for this package.

**Comment by adrn** [comment]
A markdown file and a .bib file - is that all I need to provide to JOSS @dfm ?

Can you have a look at the `papers/` path and see if it looks ok?

**Comment by adrn** [comment]
(or maybe @arfon would be willing to take a peek!)

**Comment by arfon** [comment]
:wave: @adrn. A couple of things:

- The metadata header has changed a little since @dfm last submitted (mostly the affiliations), see [this example](https://github.com/arfon/fidgit/blob/master/paper/paper.md) for how to format these data.
- We've also updated our guidance on what papers should contain. Could you take a look at the [author guidelines](http://joss.theoj.org/about#author_guidelines) and make sure you're addressing all of the bullets under _What should my paper contain?_

**Comment by adrn** [comment]
Got it -- thanks a bunch!

**Comment by dfm** [comment]
It looks to me like you've got everything in the right format now and that the requirements are checked.

**Comment by adrn** [comment]
Done http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30
